### ISSUE TITLE
User page doesn't refresh after user creation

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/abacus#1]
The user page doesn't refresh after a user creation / doesn't update the table on the page with the new user.

**Comment by Jl5her** [comment]
Was fixed with an `onsuccess=refresh()` in [admin/users.html](https://github.com/acm-mu/abacus/blob/7f66ebf50132435dfe84a53bfb0861a76f187b54/blueprints/admin/templates/admin/users.html#L46)
