### ISSUE TITLE
Standings Board updates fields based on who is viewing it

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/abacus#100]
## Summary

I would like to see that the standings board updates fields (links, names, etc.) based on who is viewing it.

### Basic example

If an unsigned in site visitor is viewing the standings board, they should not see links to team names as if they could click on them and find out more about that team. If there is a user signed in, and they are not an admin, the same behavior should apply. If they are an admin, it would link them back to their side of the platform to view information about the team.

### Motivation

It creates a cleaner UI and a better overall user experience as they aren't tricked into believing they can view information about users, etc.

**Comment by Jl5her** [comment]
If users are viewing the page their team row could be highlighted
