### ISSUE TITLE
Judges can claim submissions

### ISSUE THREAD

**Issue by Jl5her** [acm-mu/abacus#116]
To show other judges that a submission is being worked on, allow judges to claim submissions

@brad-cooley Do we want to restrict editing submissions if and only if they have the submission claimed?

**Comment by brad-cooley** [comment]
Yes, if a judge claims a submission, no other judge should be able to access it or edit it unless a judge releases/unclaims it.

**Comment by Jl5her** [comment]
Not even view it?

**Comment by brad-cooley** [comment]
I don't see a reason for them to view it if a judge is already looking at it.

**Comment by Jl5her** [comment]
Hey, can you take a look at this submission real quick
