### ISSUE TITLE
Test Data text field shrinks until it fits data with each character action

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/abacus#134]
## Description

Test Data text field shrinks until it fits data with each character action

### Steps to reproduce

Log in as an admin. Go to problems. Click on any existing problem. Navigate to the Test Data tab. Click any test and click in the "Input" or "Output" text fields. Do any character input or action (delete, add, etc.)

### Expected result

Text field size should not change.

### Actual result

Text field shrinks with every character action until it has shrunk down to the data that occupies the field.

**Comment by Jl5her** [comment]
The shrinking was a side effect of trying to grow the text area when the content is larger than the text area so you can match line by line up with the output. 

Do we want the text areas to be a constant height and if the content exceeds the text area the users can scroll?

**Comment by brad-cooley** [comment]
Yeah, that would be ideal.
