### ISSUE TITLE
401 Error while page is rendering

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/abacus#30]
## Description

401 Unauthorized Errors given while waiting for certain pages to load on team accounts.

### Steps to reproduce

- Log into any team account and try loading a page like Problems or Submissions (a page that requires permissions to view).

### Expected result

Page should load without displaying 401 error or should display a loading icon while waiting for data from backend.

### Actual result

401 error displayed while waiting for data to finish loading.

### Evidence

![Example](https://user-images.githubusercontent.com/5460503/108796183-64d7f580-7545-11eb-8c14-f527c8790fb8.gif)

**Comment by Jl5her** [comment]
@brad-cooley I believe this was fixed with #68. App doesn't show pages until auth check has finished, and while pages are waiting for data they show loader. 

Please retest

**Comment by brad-cooley** [comment]
Fixed with #68. Thank you.
