### ISSUE TITLE
Can't log in after a failed attempt without reloading the page

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/abacus#60]
## Description

User cannot log into the app after a failed attempt. In order to do this, they must reload the page and try again.

### Steps to reproduce

Try to log into an account with an incorrect password. Now, enter the correct password and try to log in and the request is still denied.

### Expected result

The user should be able to log in.

### Actual result

User log in is denied.

**Comment by Jl5her** [comment]
@brad-cooley  I believe this is a problem with the states. After submitting the form the states for username and password are empty, but the DOM still shows the username and password. 

The workaround for this would be after every fail attempt, retype username and password.

In #68, the states are cleared after the fetch fails which clears the DOM as well.

Please retest

**Comment by brad-cooley** [comment]
Fixed with #68. Thank you.
