### ISSUE TITLE
User checkboxes not changing state when individually clicked

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/abacus#61]
## Description

Checkbox doesn't work on users page.

### Steps to reproduce

Login as an admin. Head to the users page. Try to click the checkbox of a singular user.

### Expected result

Checkbox should become checked/unchecked depending on state

### Actual result

Checkbox does not change states.

**Comment by Jl5her** [comment]
@brad-cooley I believe this has been fixed in directly with #68.

My testing suggests so, please retest and close if appropriate

**Comment by brad-cooley** [comment]
Fixed with #68. Thank you.
